site_name: PyFarm
site_url: https://example.com/
nav:
  - Home:
      - Welcome: index.md
  - Getting Started:
      - Project Information: getting_started/information.md
      - Local Setup: getting_started/local_setup.md
      - Deployment: getting_started/deployment.md
  - Technical Details:
      - PyFarm API: tech_docs/api.md
      - PyFarm App: tech_docs/app.md
      - PyFarm Data Model: tech_docs/data.md
      - PyFarm Devices: tech_docs/devices.md
      - PyFarm Migrations: tech_docs/migrations.md
  - Using The App:
      - First Login: app/login.md
theme: readthedocs
extra_css: [extra.css]
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
